### ISSUE TITLE
Invalid coordinates on some polygons

### ISSUE THREAD

**Issue by alukach** [Turfjs/turf-centroid#5] opened 2015-01-30 06:34 UTC
I am running in to an issue where `centroid` raises an error (`Invalid coordinates`) on about 50% of the MultiPolygons that I'm creating from a geojson file.  The json validates (http://geojsonlint.com/) and appear on the map as expected.  This error also occurs when using `explode` (although on initial testing, `center` seems to work as expected).  This is with Turf `v1.3.0`

An example can be seen here: http://jsfiddle.net/Lpczq879/2/

**Comment by morganherlocker** [comment] 2015-01-30 07:11
Thanks for reporting @alukach. I will [look into this](https://github.com/Turfjs/turf-meta/issues/4) tomorrow.

**Comment by alukach** [comment] 2015-01-30 17:01
Thanks for the quick response.

Looking into this, I realized that while `center` doesn't raise an error, its return value is obviously incorrect.  Additionally, I noticed that the `centroid` return value is very incorrect as well.  I'm assuming that there's something wrong with the data, although I'm at a loss for what that would be.

Example updated: http://jsfiddle.net/Lpczq879/4/

**Comment by morganherlocker** [comment] 2015-02-05 23:42
ok, added your 'Bad' case as a fixture to this and turf-center. [results](https://github.com/Turfjs/turf-center/issues/5#issuecomment-73153632)

While I could reproduce this issue in 1.3.0, it looks like recent work has resolved this. Either way, I improved tests to both modules, so we can be sure things don't break in the future (in the same way at least :wink: ).

I will close this as soon as the next turf release ships, unless there are other concerns.

**Comment by alukach** [comment] 2015-02-06 01:28
Great.  Mysterious that it was failing but glad to have it added to test fixtures.  Upgrading to 1.3.5 appears to solve the issue: http://jsfiddle.net/Lpczq879/5/

Thanks.

**Comment by morganherlocker** [comment] 2015-02-10 18:54
All set here w/ 1.4.0

**Closed as completed by morganherlocker** 2015-02-10 18:54 UTC
